#!/bin/bash
set -e
if ! id bayeos > /dev/null 2>&1 
then	
	useradd bayeos
fi

service postgresql start  

chmod +x /usr/share/bayeos-gateway/*.sh
su - postgres -c /usr/share/bayeos-gateway/pg_postinst.sh

mkdir -p /var/log/bayeos
chown -R bayeos:bayeos /var/lib/bayeos-gateway /var/log/bayeos

chmod 700 /var/lib/bayeos-gateway/bayeos-gateway.jar
ln -sf /etc/bayeos-gateway/application.properties /var/lib/bayeos-gateway/application.properties

systemctl enable bayeos-gateway.service
service bayeos-gateway start  

a2enmod proxy proxy_http ssl remoteip
a2enconf bayeos-gateway.conf
service apache2 reload
